# fly.toml app configuration file generated for telegram-recipe-bot on 2026-07-23T00:53:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-recipe-bot'
primary_region = 'jnb'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
